// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: model/schema.proto

package model

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ShopperAccount) Validate() error {
	for _, item := range this.Addresses {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Addresses", err)
			}
		}
	}
	for _, item := range this.Causes {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Causes", err)
			}
		}
	}
	if this.CreditCard != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreditCard); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreditCard", err)
		}
	}
	for _, item := range this.SubscribedTopics {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("SubscribedTopics", err)
			}
		}
	}
	return nil
}
func (this *CreditCard) Validate() error {
	if this.CreditCardBillingAddress != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreditCardBillingAddress); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreditCardBillingAddress", err)
		}
	}
	return nil
}
func (this *Address) Validate() error {
	return nil
}
func (this *SubscribedTopic) Validate() error {
	if this.SubscribedTopic != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SubscribedTopic); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SubscribedTopic", err)
		}
	}
	return nil
}
func (this *Topic) Validate() error {
	if this.TopicCoverImage != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.TopicCoverImage); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("TopicCoverImage", err)
		}
	}
	return nil
}
func (this *Image) Validate() error {
	if this.Metadata != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Metadata); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Metadata", err)
		}
	}
	return nil
}
func (this *ImageMeta) Validate() error {
	return nil
}
