// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package proto

import (
	"github.com/BlackspaceInc/BlackspacePlatform/src/services/shopper_service/pkg/graphql_api/model"
)

type Response interface {
	IsResponse()
}

type Address struct {
	ID           *int    `json:"id"`
	Street       *string `json:"street"`
	Province     *string `json:"province"`
	City         *string `json:"city"`
	ZipCode      *string `json:"zipCode"`
	Country      *string `json:"country"`
	CountryCode  *string `json:"countryCode"`
	ProvinceCode *string `json:"provinceCode"`
}

type AddressInput struct {
	Street       *string `json:"street"`
	Province     *string `json:"province"`
	City         *string `json:"city"`
	ZipCode      *string `json:"zipCode"`
	Country      *string `json:"country"`
	CountryCode  *string `json:"countryCode"`
	ProvinceCode *string `json:"provinceCode"`
}

type CreditCard struct {
	ID                       *int     `json:"id"`
	CardNumber               *string  `json:"cardNumber"`
	CardBrand                *string  `json:"cardBrand"`
	ExpiresSoon              *bool    `json:"expiresSoon"`
	ExpirationMonth          *int     `json:"expirationMonth"`
	ExpirationYear           *int     `json:"expirationYear"`
	FirstDigits              *string  `json:"firstDigits"`
	LastDigits               *string  `json:"lastDigits"`
	MaskedNumber             *string  `json:"maskedNumber"`
	CardHolderName           *string  `json:"cardHolderName"`
	CreditCardBillingAddress *Address `json:"creditCardBillingAddress"`
}

type CreditCardInput struct {
	CardNumber               *string       `json:"cardNumber"`
	CardBrand                *string       `json:"cardBrand"`
	ExpiresSoon              *bool         `json:"expiresSoon"`
	ExpirationMonth          *int          `json:"expirationMonth"`
	ExpirationYear           *int          `json:"expirationYear"`
	FirstDigits              *string       `json:"firstDigits"`
	LastDigits               *string       `json:"lastDigits"`
	MaskedNumber             *string       `json:"maskedNumber"`
	CardHolderName           *string       `json:"cardHolderName"`
	CreditCardBillingAddress *AddressInput `json:"creditCardBillingAddress"`
}

type Image struct {
	ID       *int       `json:"id"`
	Metadata *ImageMeta `json:"metadata"`
	BlobURL  *string    `json:"blobUrl"`
	AltText  *string    `json:"altText"`
}

type ImageInput struct {
	Metadata *ImageMetaInput `json:"metadata"`
	BlobURL  *string         `json:"blobUrl"`
	AltText  *string         `json:"altText"`
}

type ImageMeta struct {
	Width     *int    `json:"width"`
	Height    *int    `json:"height"`
	RedData   *string `json:"redData"`
	GreenData *string `json:"greenData"`
	BlueData  *string `json:"blueData"`
}

type ImageMetaInput struct {
	Width     *int    `json:"width"`
	Height    *int    `json:"height"`
	RedData   *string `json:"redData"`
	GreenData *string `json:"greenData"`
	BlueData  *string `json:"blueData"`
}

type OperationResponse struct {
	Message *string `json:"message"`
	Code    *int    `json:"code"`
	Status  *bool   `json:"status"`
}

func (OperationResponse) IsResponse() {}

type ShopperAccountInput struct {
	FirstName           *string                 `json:"firstName"`
	LastName            *string                 `json:"lastName"`
	Email               *string                 `json:"email"`
	Username            *string                 `json:"username"`
	Phone               *string                 `json:"phone"`
	IsActive            *bool                   `json:"isActive"`
	AcceptsMarketing    *bool                   `json:"acceptsMarketing"`
	AcceptedMarketingAt *string                 `json:"acceptedMarketingAt"`
	Addresses           []*AddressInput         `json:"addresses"`
	Tags                []*string               `json:"tags"`
	Causes              []*SubscribedTopicInput `json:"causes"`
	CreditCard          *CreditCardInput        `json:"creditCard"`
	SubscribedTopics    []*SubscribedTopicInput `json:"subscribedTopics"`
	Password            *string                 `json:"password"`
}

type ShopperAccountMutation struct {
	ShopperAccount *ShopperAccountInput `json:"shopperAccount"`
	AuthnID        *string              `json:"authnId"`
}

type ShopperAccountResponse struct {
	Message *string               `json:"message"`
	Code    *int                  `json:"code"`
	Status  *bool                 `json:"status"`
	Account *model.ShopperAccount `json:"account"`
}

func (ShopperAccountResponse) IsResponse() {}

type ShopperAccountsResponse struct {
	Message *string                 `json:"message"`
	Code    *int                    `json:"code"`
	Status  *bool                   `json:"status"`
	Account []*model.ShopperAccount `json:"account"`
}

func (ShopperAccountsResponse) IsResponse() {}

type SubscribedTopic struct {
	ID              *int    `json:"id"`
	SubscribedTopic *Topic  `json:"subscribedTopic"`
	SubscribedAt    *string `json:"subscribedAt"`
	Description     *string `json:"description"`
}

type SubscribedTopicInput struct {
	SubscribedTopic *TopicInput `json:"subscribedTopic"`
	SubscribedAt    *string     `json:"subscribedAt"`
	Description     *string     `json:"description"`
}

type Topic struct {
	ID              *int      `json:"id"`
	Name            *string   `json:"name"`
	Tags            []*string `json:"tags"`
	TopicCoverImage *Image    `json:"topicCoverImage"`
}

type TopicInput struct {
	Name            *string     `json:"name"`
	Tags            []*string   `json:"tags"`
	TopicCoverImage *ImageInput `json:"topicCoverImage"`
}
