// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: model/schema.proto

package model

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *BusinessAccount) Validate() error {
	if this.PhoneNumber != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PhoneNumber); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PhoneNumber", err)
		}
	}
	if this.Media != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Media); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Media", err)
		}
	}
	if this.TypeOfBusiness != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.TypeOfBusiness); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("TypeOfBusiness", err)
		}
	}
	if this.MerchantType != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.MerchantType); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("MerchantType", err)
		}
	}
	if this.PaymentDetails != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PaymentDetails); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PaymentDetails", err)
		}
	}
	if this.ServicesManagedByBlackspace != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ServicesManagedByBlackspace); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ServicesManagedByBlackspace", err)
		}
	}
	if this.FounderAddress != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.FounderAddress); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("FounderAddress", err)
		}
	}
	if this.SubscribedTopics != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SubscribedTopics); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SubscribedTopics", err)
		}
	}
	return nil
}
func (this *Topics) Validate() error {
	return nil
}
func (this *Media) Validate() error {
	return nil
}
func (this *Address) Validate() error {
	if this.Birthdate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Birthdate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Birthdate", err)
		}
	}
	return nil
}
func (this *DateOfBirth) Validate() error {
	return nil
}
func (this *ServicesManagedByBlackspace) Validate() error {
	return nil
}
func (this *PaymentProcessingMethods) Validate() error {
	for _, item := range this.PaymentOptions {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("PaymentOptions", err)
			}
		}
	}
	for _, item := range this.Medium {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Medium", err)
			}
		}
	}
	return nil
}
func (this *PaymentMedium) Validate() error {
	return nil
}
func (this *PaymentOptions) Validate() error {
	return nil
}
func (this *BusinessType) Validate() error {
	if this.Category != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Category); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Category", err)
		}
	}
	if this.SubCategory != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SubCategory); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SubCategory", err)
		}
	}
	return nil
}
func (this *BusinessCategory) Validate() error {
	return nil
}
func (this *BusinessSubCategory) Validate() error {
	return nil
}
func (this *MerchantType) Validate() error {
	return nil
}
func (this *PhoneNumber) Validate() error {
	if this.Type != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Type); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Type", err)
		}
	}
	return nil
}
func (this *PhoneType) Validate() error {
	return nil
}
