on: push
name: Authentication Handler Service
jobs:
  checks:
    name: Authentication Service CI Workflow
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/authentication_handler_service
    steps:
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Checkout Development Branch
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Validate Helm chart
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            ls -al
            helmv3 template ./src/services/authentication_handler_service/charts/authentication_handler_service | kubeval --strict
      - name: Validate Kustomization
        uses: stefanprodan/kube-tools@v1
        continue-on-error: true
        with:
          command: |
            kustomize build ./src/services/authentication_handler_service/kustomize | kubeval --strict
            kustomize build ./src/services/authentication_handler_service/kustomize | conftest test -p .github/policy -
      - name: Build code base
        working-directory: ./src/services/authentication_handler_service
        run: make build
      - name: Build Helm Charts
        continue-on-error: true
        working-directory: ./src/services/authentication_handler_service
        run: make build-charts
      - name: Run Integration & Unit Test Cases
        working-directory: ./src/services/authentication_handler_service
        continue-on-error: true
        run: make test-suite
      - name: Build Docker Container
        working-directory: ./src/services/authentication_handler_service
        run: make build-container
      - name: Docker Build And Push
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build . --file Dockerfile --tag blackspaceinc/authentication_handler_service:dev
          docker push blackspaceinc/authentication_handler_service:dev
